from authenticated import AuthenticatedView
from login import Login
from event import EventView
from home import Home
from events import Events
from questions import Questions
from answers import Answers
from register import RegisterView
from new_event import NewEvent
from delete_event import DeleteEvent
from invitations import Invitations
from delete_invitation import DeleteInvitation
